# homepage/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('passenger/', views.passenger_page, name='passenger_page'),
    path('driver/', views.driver_page, name='driver_page'),
    path('register/', views.register_page, name='register_page'),
    path('login/', views.login_page, name='login_page'),
    path('passenger_attributes/', views.passenger_attributes, name='passenger_attributes'),
    path('login_attributes/', views.login_attributes, name='login_attributes'),
    path('login_check/', views.login_check, name='login_check'),
    path('bookings/', views.bookings_page, name='bookings_page'),
    path('ride_history/', views.ride_history_page, name='ride_history_page'),
    path('profile/', views.profile_page, name='profile_page'),
    path('edit_profile/', views.edit_profile_page, name='edit_profile_page'),
    path('logout/', views.logout_user, name='logout_user'),
    path('features/', views.features_page, name='features_page'),
    path('pricing/', views.pricing_page, name='pricing_page'),
    path('notifications/', views.notifications_page, name='notifications_page'),
    path('help_and_support/', views.help_and_support_page, name='help_and_support_page'),
    path('terms_of_service/', views.terms_of_service_page, name='terms_of_service_page'),
    path('privacy_policy/', views.privacy_policy_page, name='privacy_policy_page'),
    path('about_us/', views.about_us_page, name='about_us_page'),
    path('disabled_attributes/', views.disabled_attributes_page, name='disabled_attributes_page'),
    path('search/', views.search_page, name='search_page'),
    path('filters/', views.filters_page, name='filters_page'),
    path('results/', views.results_page, name='results_page'),
    path('book_ride/', views.book_ride_page, name='book_ride_page'),
    path('book_ride_attributes/', views.book_ride_attributes_page, name='book_ride_attributes_page'),
    path('driver_register/', views.driver_register_page, name='driver_register_page'),
    path('driver_login/', views.driver_login_page, name='driver_login_page'),
    path('driver_attributes/', views.driver_attributes_page, name='driver_attributes_page'),
    path('driver_login_check/', views.driver_login_check, name='driver_login_check'),
    path('vehicle_verification/', views.vehicle_verification_page, name='vehicle_verification_page'),
    path('notifications_area/', views.notifications_area_page, name='notifications_area_page'),
    path('conversations_panel/', views.conversations_panel_page, name='conversations_panel_page'),
    path('ride_management/', views.ride_management_page, name='ride_management_page'),
    path('manage_rides/', views.manage_rides_page, name='manage_rides_page'),
    path('payment_details/', views.payment_details_page, name='payment_details_page'),
    path('reviews_ratings/', views.reviews_ratings_page, name='reviews_ratings_page'),
    path('driver_analytics/', views.driver_analytics_page, name='driver_analytics_page'),
]
