# Generated by Django 4.2.3 on 2023-08-18 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cre_Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('mobilenumber', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('email', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='publish_ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des1', models.CharField(max_length=50, null=True)),
                ('des2', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('seats', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('carname', models.CharField(max_length=50, null=True)),
                ('carnumber', models.CharField(max_length=10, null=True)),
                ('license', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
